version: 0.0
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: "arn:aws:ecs:us-east-1:026090542851:task-definition/ecs-html:1"
        LoadBalancerInfo:
          ContainerName: "ecshtml"
          ContainerPort: 80

