
version: 0.2

phases:
  pre_build:
    commands:
      - echo "Installing dependencies..."
      - echo "Logging in to Amazon ECR..."
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 02609054285.dkr.ecr.us-east-1.amazonaws.com
      - IMAGE_TAG=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)

  build:
    commands:
      - echo "Building Docker image..."
      - docker build -t my-app:$IMAGE_TAG .
      - docker tag my-app:$IMAGE_TAG 026090542851.dkr.ecr.us-east-1.amazonaws.com/my-app:$IMAGE_TAG

  post_build:
    commands:
      - echo "Pushing Docker image to ECR..."
      - docker push 026090542851.dkr.ecr.us-east-1.amazonaws.com/my-app:$IMAGE_TAG
      - echo '[{"name":"ecs-container","imageUri":"026090542851.dkr.ecr.us-east-1.amazonaws.com/my-app:'$IMAGE_TAG'"}]' > imagedefinitions.json

artifacts:
  files:
    - imagedefinitions.json
