version: 0.2

env:
  variables:
    IMAGE_TAG: "latest"

phases:
  pre_build:
    commands:
      - echo "Logging in to Amazon ECR..."
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 026090542851.dkr.ecr.us-east-1.amazonaws.com
  build:
    commands:
      - echo "Building the Docker image..."
      - docker build -t ecr-html:$IMAGE_TAG .
      - echo "Listing built Docker images..."
      - docker images
      - echo "Tagging Docker image..."
      - docker tag ecr-html:$IMAGE_TAG 026090542851.dkr.ecr.us-east-1.amazonaws.com/ecr-html:$IMAGE_TAG
  post_build:
    commands:
      - echo "Pushing Docker image to Amazon ECR..."
      - docker push 026090542851.dkr.ecr.us-east-1.amazonaws.com/ecr-html:$IMAGE_TAG
      - echo "Creating imagedefinitions.json file..."
      - printf '[{"name":"ecshtml","imageUri":"026090542851.dkr.ecr.us-east-1.amazonaws.com/ecr-html:%s"}]' $IMAGE_TAG > imagedefinitions.json
artifacts:
  files:
    - imagedefinitions.json
